version: '3.8'
services:
  web:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_SUPABASE_URL=http://localhost:54321
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=your-anon-key-here
    depends_on:
      - supabase

  supabase:
    image: supabase/local-dev:latest
    ports:
      - '54321:54321'  # API (REST)
      - '54322:54322'  # DB
    environment:
      - SUPABASE_DB_PASSWORD=postgres
    volumes:
      - supabase_data:/var/lib/postgresql/data

volumes:
  supabase_data:
